# Generated by Django 4.2.3 on 2023-07-08 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_animal_owner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Animal',
        ),
    ]
