# Generated by Django 4.2.3 on 2023-07-09 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_animal_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='age',
            field=models.CharField(choices=[('PP', 'Szczenię'), ('AD', 'Dorosły'), ('EL', 'Staruszek')], max_length=20),
        ),
    ]
