# Generated by Django 4.2.3 on 2023-07-10 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_animal_slug_alter_animal_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='static_url',
            field=models.FilePathField(default='null'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='photo',
            field=models.ImageField(upload_to='main/static/images/uploads'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='slug',
            field=models.SlugField(blank=True, default='null', unique=True),
        ),
    ]
