# Generated by Django 4.2.3 on 2023-07-10 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_animal_static_url_alter_animal_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='static_url',
            field=models.FilePathField(default='null'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='slug',
            field=models.SlugField(blank=True, default='null', unique=True),
        ),
    ]
