# Generated by Django 4.2.3 on 2023-07-10 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_animal_static_url_alter_animal_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='static_url',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
