# Generated by Django 4.2.3 on 2023-07-10 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_animal_static_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='age',
            field=models.CharField(choices=[('Szczenię', 'PP'), ('Dorosły', 'AD'), ('Staruszek', 'EL')], max_length=20),
        ),
        migrations.AlterField(
            model_name='animal',
            name='static_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
