# Generated by Django 4.2.3 on 2023-07-12 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_animal_age_alter_animal_static_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='color',
        ),
    ]
