# Generated by Django 4.2.3 on 2023-07-12 08:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_animal_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='color',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, size=None),
        ),
    ]
