# Generated by Django 4.2.3 on 2023-07-12 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_animal_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='color',
            new_name='colors',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='photo',
        ),
    ]
