# Generated by Django 4.2.3 on 2023-07-12 09:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_rename_color_animal_colors_remove_animal_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='photo',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(upload_to='main/static/images/uploads'), default=list, size=None),
        ),
    ]
