# Generated by Django 4.2.3 on 2023-07-18 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_animal_photos_alter_animal_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='photos',
        ),
        migrations.AddField(
            model_name='animal',
            name='photo2',
            field=models.ImageField(blank=True, upload_to='main/static/images/uploads'),
        ),
        migrations.AddField(
            model_name='animal',
            name='photo3',
            field=models.ImageField(blank=True, upload_to='main/static/images/uploads'),
        ),
    ]
