# Generated by Django 4.2.3 on 2023-07-18 09:09

from django.db import migrations, models
import django_jsonform.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_remove_animal_photos_animal_photo2_animal_photo3'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='static_urls',
            field=django_jsonform.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=500), default=list, size=None),
        ),
    ]
