# Generated by Django 4.2.3 on 2023-07-18 09:10

from django.db import migrations, models
import django_jsonform.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_animal_static_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='static_urls',
            field=django_jsonform.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=500), blank=True, default=list, size=None),
        ),
    ]
