# Generated by Django 4.2.3 on 2023-10-16 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_animal_photo_alter_animal_photo2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='photo',
            field=models.ImageField(upload_to='images/uploads'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='photo2',
            field=models.ImageField(blank=True, upload_to='images/uploads'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='photo3',
            field=models.ImageField(blank=True, upload_to='images/uploads'),
        ),
    ]
