# Generated by Django 4.2.3 on 2023-11-07 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_alter_animal_photo_alter_animal_photo2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='gender',
            field=models.CharField(choices=[('F', 'Samica'), ('M', 'Samiec')], max_length=20),
        ),
    ]
