# Generated by Django 4.2.3 on 2023-11-13 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_alter_animal_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='gender',
            field=models.CharField(choices=[('M', 'Samiec'), ('F', 'Samica')], max_length=20),
        ),
    ]
