# Generated by Django 4.2.3 on 2023-11-27 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_chat_remove_animal_static_urls_alter_animal_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='chatID',
            field=models.CharField(unique=True),
        ),
    ]
