# Generated by Django 4.2.3 on 2023-12-17 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_chatimage_alter_animal_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='colors',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='animal',
            name='gender',
            field=models.CharField(choices=[('F', 'Samica'), ('M', 'Samiec')], max_length=20),
        ),
    ]
