# Generated by Django 4.2.3 on 2023-12-17 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_alter_animal_colors_alter_animal_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='status',
            field=models.CharField(choices=[('Znaleziony', 'F'), ('Zaginiony', 'L')], default='L', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='animal',
            name='gender',
            field=models.CharField(choices=[('Samica', 'F'), ('Samiec', 'M')], max_length=20),
        ),
    ]
