# Generated by Django 4.2.3 on 2023-12-17 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_alter_animal_gender_alter_animal_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='gender',
            field=models.CharField(choices=[('Samica', 'F'), ('Samiec', 'M')], max_length=20),
        ),
        migrations.AlterField(
            model_name='animal',
            name='status',
            field=models.CharField(choices=[('Zaginione', 'L'), ('Znalezione', 'F')], max_length=20),
        ),
    ]
