# Generated by Django 4.2.3 on 2023-12-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_alter_animal_gender_alter_animal_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='status',
            field=models.CharField(choices=[('Znalezione', 'F'), ('Zaginione', 'L')], max_length=20),
        ),
    ]
