# Generated by Django 4.2.3 on 2023-12-19 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_alter_animal_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='location_name',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='animal',
            name='status',
            field=models.CharField(choices=[('Zaginione', 'L'), ('Znalezione', 'F')], max_length=20),
        ),
    ]
